### ISSUE TITLE
OAuth 2.1 komt eraan

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/OAuth-NL-profiel#12]
OAuth 2.1 gaat eraan komen. Hierin worden een aantal features deprecated. we moeten checken of dit werkt met ons profiel.

**Comment by mrtn78** [comment]
Dit issue is gesloten. [Issue 15]( https://github.com/Logius-standaarden/OAuth-NL-profiel/issues/15) gaat ook over de release van OAuth 2.1. We pakken het hierin verder op.
