### ISSUE TITLE
PKCE beschrijving in Sectie 2.3.1 klopt niet

### ISSUE THREAD

**Issue by frankvanes** [Logius-standaarden/OAuth-NL-profiel#13]
Er staat:
> Native clients MUST apply PKCE, as per RFC7636. As code_verifier the S256 method MUST be applied. Effectively this means that a Native Client MUST include a cryptographic random code_challenge of at least 128 bits of entropy and the code_challenge_method with the value S256.

Echter:
- niet de code_verifier maar de code_challenge wordt berekend middels S256 algoritme,
- niet de code_challenge maar de code_verifier is een random string met minstens 128 bits entropie (RFC7636 zegt minimaal 34 en maximaal 128 niet gereserveerde karakters (https://tools.ietf.org/html/rfc7636#section-4.1))

**Comment by mrtn78** [comment]
Dit staat in onze NL Gov toevoeging en kunnen we zelf corrigeren

**Comment by sanderke** [comment]
https://github.com/Logius-standaarden/OAuth-NL-profiel/blob/6fc0957e79265984643796c27dbf0778d512aca5/Client%20Profiles.md?plain=1#L95-L97

**Comment by mrtn78** [comment]
ik heb deze wijziging meegenomen in PR #45 
het betreft dezelfde 2 regels iGov-NL additional content.
