### ISSUE TITLE
OAuth 2.1

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/OAuth-NL-profiel#15]
OAuth 2.1 is in aantocht: https://oauth.net/2.1/
Dit biedt de kans om het NEderlands profiel OAuth te versimpelen omdat een aantal keuzes die wij in het profiel maken (zoals PKCE) straks in de OAuth 2.1 standaard staan. Dit levert bij gelijkblijvende fucntionaliteit een korter en leesbaarder document op.

**Comment by martinborgman** [comment]
Het lijkt er op dat deze draft dood is https://datatracker.ietf.org/doc/draft-parecki-oauth-v2-1/

**Comment by mrtn78** [comment]
[Issue 12](https://github.com/Logius-standaarden/OAuth-NL-profiel/issues/12) is gesloten ivm de overlap in dit issue:
@fterpstra vermelde in issue 12 ook "OAuth 2.1 gaat eraan komen. Hierin worden een aantal features deprecated. we moeten checken of dit werkt met ons profiel."

De laatste draft is op 15-03-2021 gepubliceerd op [https://datatracker.ietf.org/doc/draft-ietf-oauth-v2-1/02/](https://datatracker.ietf.org/doc/draft-ietf-oauth-v2-1/02/)

**Comment by kad-borgmm** [comment]
De voorgang op OAuth 2.0 leek heel even stilgevallen, maar er is een nieuwe draft [draft-ietf-oauth-v2-1-02](https://www.ietf.org/archive/id/draft-ietf-oauth-v2-1-02.html)

**Comment by mrtn78** [comment]
voorstel is deze voorlopig on hold te zetten totdat versie 2.1 definitief is. indien men zelf een vooronderzoek wil doen dan graag de resultaten presenteren in de werkgroep.
