### ISSUE TITLE
Claims for Authorization Outside of Delegation Scenarios

### ISSUE THREAD

**Issue by ghost** [Logius-standaarden/OAuth-NL-profiel#16]
I think we should address the issue of "Claims for Authorization Outside of Delegation Scenarios" and follow the guidelines outlined in the draft RFC [JSON Web Token (JWT) Profile for OAuth 2.0 Access Tokens; section 2.2.3 Authorization Claims](https://tools.ietf.org/html/draft-ietf-oauth-access-token-jwt-12#section-2.2.3).
This RFC is approved.

**Comment by mrtn78** [comment]
todo:
- nagaan of dit issue outdated is?
- nagaan in het NLGov profiel of we verwijzen naar de actuele JWT standaarden?

nb. door te verwijzen naar de actuele JWT specificatie adresseren we impliciet gelijk ook dit issue.

**Comment by mrtn78** [comment]
Verder onderzoeken toepassing en verwijzing naar https://datatracker.ietf.org/doc/html/rfc9068

**Comment by hhudig** [comment]
[rfc9396](https://www.rfc-editor.org/rfc/rfc9396) is aanvullend op rc9068 section 2.3.3 te maken. Is generieker van opzet dan paragraaf 3.2.2 en past daarom in mijn ervaring vaak beter.
Wordt ook genoemd in sommige nieuwere profielen zoals FAPI 2.0 en verifiable credentials.

**Comment by martinborgman** [comment]
RFC 9396 OAuth 2.0 Rich Authorization Requests gaat volgens mij over rechten in the authorization flow en dat is iets anders dan waar dit issue oorspronkelijk voor was. Ik ga deze RFC eerst even aandachtig lezen en dan beoordeel ik wel of hier een ander issue en een nieuwe PR van maak of dat we dit pinnen dit issue moeten doen.

**Comment by hhudig** [comment]
Hi Martin,

Volgens mij is de bedoeling van de rfc dat je die niet alleen in de authorization flow (bij consent) kunt toepassen, maar ook daarna, binnen een JWT access token. Zie https://www.rfc-editor.org/rfc/rfc9396#name-token-introspection. en ook  https://justinsecurity.medium.com/applying-rar-in-oauth-2-and-gnap-76a7bae442da

In toepassingen waar ik aan heb gewerkt gebruikten we een opaque token (of jwt token met weinig inforatie) aan de voorkant wat dan omgewisseld werd met een token met specifieke autorisatie context voor de ontvangende (micro)service. De informatie getransformeerd naar een formaat dat de microservice gemakkelijk kon mappen op zijn eigen autorisatie metagegevens at-rest en autorisatieregels. Het ging vaak om allerlei verschillende informatie zoals, zaaktypen, status, locatie, rol of vertaalde informatie zoals regels rondom betrokkenen. In andere gevallen waren en minder gegevens nodig, of vertaalde de applicatie zelf meer. RAR biedt vrijheid om eigen attributen te definiëren, en paste daarom goed.

**Comment by martinborgman** [comment]
Dit issue gaat over rollen, rechten of entitlements die de resource owner heeft, buiten de authorization flow, die van betekenis zijn voor de resources server. Denk dan bijvoorbeeld aan rechten in een directory (AD).

RAR gaat over autorisaties binnen de authorization flow die niet te modelleren zijn in scopes, zoals het namens de resource owner mogen ondertekenen van een document of het overboeken van een bedrag. Nadat de resource owner goedkeuring gegeven heeft (consent), komt er een authorization_details claim in het access token en/of token introspection response.

Omdat ik deze use case interessant vind voor ons profiel heb ik hiervoor issue #49 aangemaakt.
