### ISSUE TITLE
Toevoegen Client Credentials Flow

### ISSUE THREAD

**Issue by martinborgman** [Logius-standaarden/OAuth-NL-profiel#17]
Er is o.a. vanuit VNG realisatie een verzoek gedaan om de Client Credentials Flow op te nemen.
Voor m2m koppelingen hanteren we als overheid mTLS met PKI-Overheid certificaten. Het probleem wat VNG hiermee heeft is dat het PKI-Overheid certificaat in de huidige vorm slechts een organisatie of afdeling van een organisatie identificeert en dat die identiteit bij meerdere organisaties rechten heeft om dingen te doen.  Men zou dus graag identiteiten willen kunnen gebruiken die alleen rechten hebben op een beperkte set API's. En vanuit API's komen dan vrij makkelijk bij de Client Credentials Flow. De Client heeft  dan de beperkte rechten.

**Comment by mrtn78** [comment]
@fterpstra kan je hier op reageren /aanvullen nav de recente discussie bij het KP op 24-11-2021. Ik neem aan dat dit onderwerp toen ook aan bod is gekomen.

**Comment by mrtn78** [comment]
Zie issue #3
dit issue gesloten ivm dubbelingen
