### ISSUE TITLE
Client Credentials Flow - 1.3.3.4 Client Keys

### ISSUE THREAD

**Issue by fterpstra** [Logius-standaarden/OAuth-NL-profiel#3]
(binnengekomen via webformulier)
opmerking:
De optie   om het client credentials grant type te gebruiken wordt geschrapt. Dat is   zonde, want deze vorm heeft toegevoegde waarde bij machine-to-machine   communicatie.

oplossing:
Niet schrappen.

**Comment by rschaar-logius** [comment]
client credentials grant type dient een hele andere use case. Die use case is buiten scope voor het profiel zoals nu opgesteld. In een latere uitbreiding of ander profiel kunnen client credentials, indien relevant, opgenomen worden.

**Comment by fterpstra** [comment]
opmerking jan-jaap via mail: Zoals je weet gebruiken we dit ook bij het DSO. Er zijn wel alternatieven voor deze grant type (geen Oauth gebruiken) maar het is wel zo fraai om voor alle verbindingen OAuth te gebruiken. Ik ben er op zich voorstander van om de client credentials grant erin te laten (voor DSO zou het mooi zijn omdat we dan meer conform het Nederlandse profiel opereren). Er kunnen wel opmerkingen bij worden gezet dat er verstandig met deze grant omgegaan moet worden. Verder wil ik nog opmerken dat deze grant type niet inherent onveilig is zoals bijvoorbeeld de implicit type, tot mijn kennis in ieder geval. Ik hoor graag of hij weer erin komt.

**Comment by fterpstra** [comment]
We zien hier een duidelijke behoefte voor het uitwerken van de machine-machine usecase. Deze zetten we op de backlog als nieuwe feature voor een volgende versie van het Nederlands profiel OAuth. Het kost ons nu teveel doorlooptijd om deze voor de huidige versie degelijk uit te werken.
We zullen dan meteen overwegen of we het uitdelen van accesstokens op basis van mutual TLS met PKIOverheid certificaten te ondersteunen.

**Comment by martinborgman** [comment]
Bij het Kadaster heb ik nu ook behoefte aan het client credentials grant type.

**Comment by adgerrits** [comment]
Verbaast me vanaf het begin dat client credentials flow er niet in zit want wordt zeer intensief gebruikt binnen de overheid. Zie dat de vraag nu meer dan 3 jaar uitstaat dus misschien opnieuw op de agenda zetten? Zou wat mij betreft prio 1 zijn want niet opnemen betekent in praktijk dat iedereen net even wat anders doet.

**Comment by gkoks** [comment]
Is het al bekend wanneer de client credentials flow onderdeel wordt van de NL Gov Assurance standaard voor Oauth2? Hier is vanuit de markt een sterke behoefte aan.

**Comment by fterpstra** [comment]
We werken er aan, maar kunnen nog geen beloftes doen over wanneer het formeel wordt vastgesteld.

**Comment by mrtn78** [comment]
gesloten tijdens overleg 11-04-2024
