### ISSUE TITLE
Allow direct access clients to authenticate with an X.509 certificate

### ISSUE THREAD

**Issue by ronaldkoster** [Logius-standaarden/OAuth-NL-profiel#34]
### Omschrijving

De Vereniging van Nederlandse Gemeenten(VNG) heeft de standaard Federated Service Connectivity (FSC) ontwikkeld. In deze standaard staat beschreven hoe o.a. koppelingen tot HTTP API's kunnen worden opgezet en beheerd. FSC maakt gebruik van OAuth 2.0 om een koppeling tot een API te autoriseren. Hiervoor wordt de client credential flow gebruikt. FSC gebruikt certificaten om een client te authenticeren bij de Authorization server. Het gebruik van certificaten wordt niet toegestaan in het OAuth NL profiel. Het profiel verplicht het gebruik van een JWT waarin de identiteit van de client is vastgelegd ([RFC 7523](https://www.rfc-editor.org/rfc/rfc7523)).

Het voorstel is om ook PKI-overheid certificaten te mogen gebruiken om een client te authenticeren bij de Authorization server. Dit betreft alleen direct access clients die de client credential flow gebruiken.

PR: https://github.com/Logius-standaarden/OAuth-NL-profiel/pull/33

### Naam

Ronald Koster

### Email

ronald.koster@vng.nl

### Organisatie

VNG

**Comment by martinborgman** [comment]
Ter aanvulling, het huidige profiel gebruikt ook een PKI-Overheid certificaat om de JWT mee te ondertekenen.
Verder is het van belang om te vermelden dat het Client Id gebruikt wordt als identiteit van de client en de client registratie. Dat geldt ook bij gebruik van [RFC 8705](https://www.rfc-editor.org/rfc/rfc8705)
