### ISSUE TITLE
Authorization servers SHOULD support dynamic client registration

### ISSUE THREAD

**Issue by mrtn78** [Logius-standaarden/OAuth-NL-profiel#39]
in paragraaf [3.1.3 Dynamic Registration](https://logius-standaarden.github.io/OAuth-NL-profiel/#dynamic-registration) is een  wijziging doorgevoerd door een strikeout die was opgenomen in de oude versie zonder client credentials en nu is teruggedraaid :(Clients MUST NOT dynamically register for the client credentials grant type. ) In lijn met deze aanpassing is het wenselijk om ook een aanpassing in de aanvullende content te maken te weten:

> iGov-NL : Additional content
> 
> In this version of iGov-NL we follow iGov for the requirement that the Authorization servers **MUST** support dynamic client registration.
> 

graag vervangen door 

> iGov-NL : Additional content
> 
> In this version of iGov-NL we follow iGov for the requirement that the Authorization servers **SHOULD** support dynamic client registration.

**Comment by sanderke** [comment]
De zinsnede "we follow iGov" past niet meer na deze wijziging, want in de iGov tekst staat MUST:
https://github.com/Logius-standaarden/OAuth-NL-profiel/blob/831d3cbbe46413a5a209a90445c105511e568be8/Authorization%20Server%20Profile.md?plain=1#L38
