### ISSUE TITLE
Tekstblok te verwijderen

### ISSUE THREAD

**Issue by adgerrits** [Logius-standaarden/OAuth-NL-profiel#51]
### Soort

- [X] Tekstuele fout
- [x] Verbetersuggestie
- [x] Onduidelijke tekst

### Omschrijving

Het tekstblok "In this use case a (public/governmental) service is offered via an API. The service will be consumed by the User using a client, that can be any arbitrary, non-trusted application. For provisioning the service, the service provider requires an identifier of the User. The identifier of the User can be either an arbitrary (self-registered) identifier or a formal identifier (citizen number or other restricted, registered ID). Upon service provisioning, the service uses the identifier of the User for access control within the service." lijkt per ongeluk te zijn blijven staan (?). De 2 use cases worden daarna pas beschreven. 
Verder staat in de regel erboven een spelfoutje: "som common concepts".

### Naam

Ad Gerrits

### Email

ad.gerrits@vng.nl

### Organisatie

VNG

**Comment by mrtn78** [comment]
Dit tekstblok hoort idd bij de authorization code flow use case. zie ook v1 https://gitdocumentatie.logius.nl/publicatie/api/oauth/v1.0/

**Comment by mrtn78** [comment]
2 commits gemaakt in de branch https://github.com/Logius-standaarden/OAuth-NL-profiel/tree/patch_publieke_consultatie
- https://github.com/Logius-standaarden/OAuth-NL-profiel/commit/29031af0abae47ec08a8155bf72ede520771bab7
- https://github.com/Logius-standaarden/OAuth-NL-profiel/commit/6181c2d28accc7276aa976973dc47146976b612b

**Comment by mrtn78** [comment]
Dit issue is besproken in het Technisch overleg OAuth van 09-07-2024 en verwerkt in pull request #56 
Zie ook het verslag op https://github.com/Logius-standaarden/Overleg/tree/main/OAuth/2024-07-09
