### ISSUE TITLE
Foute verwijzing in "2.1.1 Full Client with User Delegation" 

### ISSUE THREAD

**Issue by martinborgman** [Logius-standaarden/OAuth-NL-profiel#8]
In "2.1.1 Full Client with User Delegation" staat een verwijzing naar Section 2.2. Dit moet echter Section "2.3.4 Client Keys" zijn.
Deze verwijzing was al fout in het iGov document.

**Comment by martinborgman** [comment]
In "2.3.3 Requests to the Token Endpoint" zit hetzelfde probleem.
Het probleem is eigenlijk dat informatie over de public key gecommuniceerd wordt tijdens de Client registration waar Section 2.2 over gaat. In Section 2.2 staat verder helemaal niets over public keys.
In Section 2.3.3 Client keys staat pas hoe de public keys van de client geregistreerd worden, maar deze sectie maakt deel uit van "2.3 Connection to the Authorization Server",

**Comment by mrtn78** [comment]
Ik heb een branche issue#8 aangemaakt voor het herstel van deze 2 verwijzingen en een pull request gemaakt om te bespreken in de werkgroep.
